name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Show Forge version
        run: |
          forge --version

      - name: Install dependencies
        run: |
          forge install foundry-rs/forge-std
          forge install OpenZeppelin/openzeppelin-contracts
          forge install Uniswap/v3-core
          forge install Uniswap/v3-periphery

      - name: Check dependencies
        run: |
          echo "Checking dependencies..."
          ls -la lib/
          echo "Checking if dependencies exist..."
          ls -la lib/openzeppelin-contracts/contracts/token/ERC20/ || echo "OpenZeppelin not found"
          ls -la lib/v3-core/contracts/interfaces/ || echo "v3-core not found"
          ls -la lib/v3-periphery/contracts/interfaces/ || echo "v3-periphery not found"

      - name: Run Forge fmt
        run: |
          forge fmt --check
        id: fmt

      - name: Run Forge build
        run: |
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          forge test -vvv
        id: test
